### ISSUE TITLE
Multiline function definition should probably be counted as 1 line

### ISSUE THREAD

**Issue by syrm** [object-calisthenics/phpcs-calisthenics-rules#54]
```php
    private function normalizeWriteCommand(
        string $command,
        $identifier,
        $values = null,
        array $options = []
    ): Couchbase\Document {
```
A function like that should probably be counted as 1 line and not 6 lines

**Comment by syrm** [comment]
Same thing for multiline declaration : 
```php
$data = [
  'user' => $user,
  'logger' => $logger
];
```

**Comment by TomasVotruba** [comment]
What do you refer to?

**Comment by syrm** [comment]
I think theses example should be counted as 1 line.

**Comment by TomasVotruba** [comment]
I understand that. But what sniff do you refer to?

**Comment by syrm** [comment]
Maximum line in one file.

**Comment by TomasVotruba** [comment]
I see. Ok, lets do this. 

Could you send PR for it?

**Comment by syrm** [comment]
But, if we do this, we should also remove the phpdoc in lines count then replace the limit of 200 lines to 100, and all that in default settings, are you agree ?

**Comment by TomasVotruba** [comment]
That would be great!

**Comment by syrm** [comment]
Ok i'll gonna make a PR, but i need lots of time :D

**Comment by TomasVotruba** [comment]
Take your time ;) Let me know if you need any help.

**Comment by johmanx10** [comment]
I do not completely agree with this approach. If someone were to create overly complex structures in code, that should have been solved by offloading data to some form of data storage, this would applaud that behavior. Also, a larger function signature is a sure sign of a more complex one and should not be treated like anything else. Also, a reduction of 100 seems excessive. The number of 200 is a fair boundary you may hit once or twice a year. Saying that multi line declarations must be making up for 100 lines of code for your functions is really excessive. If that is true than it is fine by me to get penalized for it, because one should consider an alternative solution for it. In weird edge cases when your code is concerned with caching huge amounts of data in PHP caches, one should simply use ignore rules to compensate.

**Comment by syrm** [comment]
You're right.
